version: '3.9'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco_projeto
      MYSQL_USER: dev_kremer
      MYSQL_PASSWORD: ienh2025
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha_rede

  api_python:
    build: ./api-python
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: dev_kremer
      DB_PASSWORD: ienh2025
      DB_NAME: banco_projeto
    depends_on:
      - mysql
    networks:
      - minha_rede

volumes:
  mysql_data:

networks:
  minha_rede:
